[Icon Theme]
Name=CoraOS
Comment=CoraOS Icon Theme - Red accents on dark
Inherits=Adwaita,hicolor
Example=folder

Directories=scalable/actions,scalable/apps,scalable/devices,scalable/places,scalable/status,scalable/mimetypes

[scalable/actions]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[scalable/apps]
Size=64
Context=Applications
Type=Scalable
MinSize=8
MaxSize=512

[scalable/devices]
Size=16
Context=Devices
Type=Scalable
MinSize=8
MaxSize=512

[scalable/places]
Size=16
Context=Places
Type=Scalable
MinSize=8
MaxSize=512

[scalable/status]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=512

[scalable/mimetypes]
Size=16
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=512
